In [2]:
import torch

In [3]:
import numpy as np

In [4]:
data = ([1,2],[3,4])

In [5]:
x_data = torch.tensor(data)

In [6]:
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [7]:
shape = (2,3,)

In [8]:
rand_tensor = torch.rand(shape)

In [9]:
ones_tensor = torch.ones(shape)

In [11]:
zeros_tensor = torch.zeros(shape)

In [12]:
print(f"Random Tensor: \n {rand_tensor} \n")

Random Tensor: 
 tensor([[0.1339, 0.6597, 0.4146],
        [0.9473, 0.1675, 0.7446]]) 



In [13]:
print(f"Ones Tensor: \n {ones_tensor} \n")

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 



In [14]:
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [16]:
tensor = torch.rand(3,4)

In [18]:
print(tensor)

tensor([[0.8484, 0.9320, 0.3506, 0.7226],
        [0.0699, 0.6039, 0.5787, 0.0909],
        [0.2456, 0.1683, 0.3425, 0.4671]])


In [19]:
print(f"shape of tensor: {tensor.shape}")

shape of tensor: torch.Size([3, 4])


In [20]:
tensor.shape

torch.Size([3, 4])

In [23]:
print("{tensor.shape}")

{tensor.shape}


In [24]:
print(f"{tensor.shape}")

torch.Size([3, 4])


In [25]:
tensor.dtype

torch.float32

In [26]:
tensor.device

device(type='cpu')

In [27]:
torch.cuda.is_available()

False

In [28]:
t1=torch.cat([tensor,tensor,tensor,tensor], dim=1)

In [29]:
t1

tensor([[0.8484, 0.9320, 0.3506, 0.7226, 0.8484, 0.9320, 0.3506, 0.7226, 0.8484,
         0.9320, 0.3506, 0.7226, 0.8484, 0.9320, 0.3506, 0.7226],
        [0.0699, 0.6039, 0.5787, 0.0909, 0.0699, 0.6039, 0.5787, 0.0909, 0.0699,
         0.6039, 0.5787, 0.0909, 0.0699, 0.6039, 0.5787, 0.0909],
        [0.2456, 0.1683, 0.3425, 0.4671, 0.2456, 0.1683, 0.3425, 0.4671, 0.2456,
         0.1683, 0.3425, 0.4671, 0.2456, 0.1683, 0.3425, 0.4671]])